[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM7

board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    moononournation/Arduino_GFX@^1.4.9
    https://github.com/me-processware/JC3248W535-Driver

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

extra_scripts =
    post:extra_scripts.py
